version: '3'

# WWWUSER=$(id -u) WWWGROUP=$(id -g) docker-compose build
# WWWUSER=$(id -u) WWWGROUP=$(id -g) docker-compose up -d

services:
    php:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                # WWWGROUP is sail command setting...
                WWWGROUP: '${WWWGROUP}'
        image: photofit-app
        ports:
            - '${APP_PORT:-80}:80'
        expose:
            - 9000
        environment:
            # WWWUSER is sail command setting...
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - './src:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql:8.0'
        ports:
            # localhost and docker-network only
            - '127.0.0.1:${FORWARD_DB_PORT:-3306}:3306'
            ## remote access allow define
            #- '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            TZ: "Asia/Tokyo"
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        environment:
            TZ: "Asia/Tokyo"
        ports:
            # localhost and docker-network only
            - '127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        environment:
            TZ: "Asia/Tokyo"
        ports:
            # localhost and docker-network only
            - 127.0.0.1:1025:1025
            ## web port
            - 8025:8025
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
